package typescript

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sst/sst/v3/internal/fs"
	"github.com/sst/sst/v3/pkg/bus"
	"github.com/sst/sst/v3/pkg/js"
	"github.com/sst/sst/v3/pkg/project/common"
)

type WarningEvent struct {
	Message string
}

var mapping = map[string]string{
	"aiBindings":                     "Ai",
	"r2BucketBindings":               "R2Bucket",
	"d1DatabaseBindings":             "D1Database",
	"durableObjectNamespaceBindings": "DurableObjectNamespace",
	"kvNamespaceBindings":            "KVNamespace",
	"queueBindings":                  "Queue",
	"serviceBindings":                "Service",
	"hyperdriveBindings":             "Hyperdrive",
	"versionMetadataBindings":        "WorkerVersionMetadata",
	"workflowBindings":               "Workflow",
	"rateLimitBindings":              "RateLimit",
}

var header = strings.Join([]string{
	"/* This file is auto-generated by SST. Do not edit. */",
	"/* tslint:disable */",
	"/* eslint-disable */",
	"/* deno-fmt-ignore-file */",
	"/* biome-ignore-all lint: auto-generated */",
	"",
	"",
}, "\n")

var footer = strings.Join([]string{
	"",
	"import \"sst\"",
	"export {}",
}, "\n")

func Generate(root string, links common.Links, ignore []string) error {
	cloudflareBindings := map[string]string{}
	for name, link := range links {
		for _, include := range link.Include {
			if include.Type == "cloudflare.binding" {
				binding := include.Other["binding"].(string)
				cloudflareBindings[name] = mapping[binding]
				break
			}
		}
	}

	packageJsons := fs.FindDownWithIgnore(root, "package.json", ignore)
	rootEnv := filepath.Join(root, "sst-env.d.ts")

	foundCloudflareTypes := false
	for _, packageJson := range packageJsons {
		packageJsonData, err := os.ReadFile(packageJson)
		if err != nil {
			continue
		}
		var data js.PackageJson
		if err := json.Unmarshal(packageJsonData, &data); err != nil {
			continue
		}
		if data.Dependencies["@cloudflare/workers-types"] != "" || data.DevDependencies["@cloudflare/workers-types"] != "" {
			foundCloudflareTypes = true
			break
		}
	}

	resources := map[string]interface{}{}
	for name, link := range links {
		if cfType := cloudflareBindings[name]; cfType != "" && foundCloudflareTypes {
			resources[name] = literal{value: `import("@cloudflare/workers-types").` + cfType}
		} else {
			resources[name] = link.Properties
		}
	}
	rootContent := renderRootFile(resources)

	for _, packageJson := range packageJsons {
		envPath := filepath.Join(filepath.Dir(packageJson), "sst-env.d.ts")

		content := ""
		if rootEnv == envPath {
			content = rootContent
		} else {
			rel, err := filepath.Rel(filepath.Dir(envPath), rootEnv)
			if err != nil {
				continue
			}
			content = renderReferenceFile(filepath.ToSlash(rel))
		}

		if err := os.WriteFile(envPath, []byte(content), 0644); err != nil {
			continue
		}
	}

	if len(cloudflareBindings) > 0 && !foundCloudflareTypes {
		bus.Publish(&WarningEvent{
			Message: "Cloudflare detected but `@cloudflare/workers-types` is not installed. Install it to get proper types for your bindings.",
		})
	}

	return nil
}

func renderRootFile(resources map[string]interface{}) string {
	var builder strings.Builder
	builder.WriteString(header)
	builder.WriteString("declare module \"sst\" {\n")
	builder.WriteString("  export interface Resource ")
	builder.WriteString(infer(resources, "  "))
	builder.WriteString("\n")
	builder.WriteString("}\n")
	builder.WriteString(footer)
	return builder.String()
}

func renderReferenceFile(rel string) string {
	var builder strings.Builder
	builder.WriteString(header)
	builder.WriteString("/// <reference path=\"")
	builder.WriteString(rel)
	builder.WriteString("\" />\n")
	builder.WriteString(footer)
	return builder.String()
}

type literal struct {
	value string
}

func infer(input map[string]interface{}, indentArgs ...string) string {
	indent := ""
	if len(indentArgs) > 0 {
		indent = indentArgs[0]
	}
	var builder strings.Builder
	builder.WriteString("{")
	builder.WriteString("\n")
	keys := make([]string, 0, len(input))
	for key := range input {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		value := input[key]
		builder.WriteString(indent + "  \"" + key + "\": ")
		if key == "type" && len(indentArgs) == 1 {
			builder.WriteString("\"")
			builder.WriteString(value.(string))
			builder.WriteString("\"")
		} else {
			switch v := value.(type) {
			case literal:
				builder.WriteString(v.value)
			case string:
				builder.WriteString("string")
			case int:
				builder.WriteString("number")
			case float64:
				builder.WriteString("number")
			case float32:
				builder.WriteString("number")
			case bool:
				builder.WriteString("boolean")
			case map[string]interface{}:
				builder.WriteString(infer(value.(map[string]interface{}), indent+"  "))
			default:
				builder.WriteString("any")
			}
		}
		builder.WriteString("\n")
	}
	builder.WriteString(indent + "}")
	return builder.String()
}
